### ISSUE TITLE
snapshot wrong picture paretrace retrace 

### ISSUE THREAD

**Issue by xinhuazhang1985** [ARM-software/patrace#10]
Hello
There's a replay issue that needs your support.

issue occurrence probability：over 1/100.

issue demo:
normal case : snapshot start- pic1-pic2-pic3-pic4-pic5-pic6-pic7-pic8-pic9 = end
this issue case : snapshot start- pic1-pic2-pic3-pic6-pic7-pic6-pic7-pic8-pic9 = end

pic4 and pic5 lost and pic6-pic7 replay twice

replay a trace file(such as :com.samsung.sdet.benchmark.t_rex.pat) with snapshot, some frames will loss and some frames are duplicate.

adb shell command:
am start -n com.arm.pa.paretrace/.Activities.RetraceActivity --ei oresW 2008 --ei oresH 1080 --ez multithread true --ez insequence true --ez force_single_window false --es fileName "/sdcard/apitrace/trace_repo/com.samsung.sdet.benchmark.t_rex.pat" --es snapshotPrefix "/sdcard/egl_dump/" --es snapshotCallset "*/frame"

 

--------------------------------Here is my debugging information----------------------------------------
I try to find why paretrace snapshot wrong picture, and  I fonnd between pic3-pic6 replay mCurCall.funcId sequence “disorder”

I print retreacer mCurCall.funcId  sequence，I found the sequence disorder when issue occured,
I want to know why retreacer mCurCall.funcId  sequence disorder!!! I should be same every time replay!
 
If you have any suggestion to debug this issue, please share to me ,thankyou~

debug code：
------------------------------------------------------------------------------

    const bool doTakeSnapshot = mOptions.mSnapshotCallSet &&
            (mOptions.mSnapshotCallSet->contains(mCurCallNo, mFile.ExIdToName(mCurCall.funcId)));

        const bool doFrameTakeSnapshot = mOptions.mSnapshotCallSet &&
            (mOptions.mSnapshotCallSet->contains(mDispatchFrameNo, mFile.ExIdToName(mCurCall.funcId)));

        const bool isSwapBuffers = (mCurCall.funcId == mExIdEglSwapBuffers || mCurCall.funcId == mExIdEglSwapBuffersWithDamage);
       //add  debug code xinhua.zhang@
        fprintf(fp,"%d : %d -( %d : %d : %d)\n",mCurCallNo,mCurCall.funcId,doTakeSnapshot,doFrameTakeSnapshot,isSwapBuffers);    
        if (doFrameTakeSnapshot && isSwapBuffers)
        {        
            if (!mOptions.mMultiThread)
            {
                // Single thread mode
                this->TakeSnapshot(mCurCallNo-1, mDispatchFrameNo);
            }
            else
            {
                SnapshotWork* work = new SnapshotWork(mCurCall.tid, mDispatchFrameNo, mCurCallNo - 1, NULL, NULL, "Snapshot", NULL);
                DispatchWork(work);
            }
        }

----------------------------------------------------------------------------------------------------------

when mCurCallNo = 1520054 , issue occur:

  trace relay mCurCall.funcId  sequence disorder during issue occur:
-------------------------------------
...
1520044 : 45 -( 0 : 0 : 0)
1520045 : 40 -( 0 : 0 : 0)
1520046 : 134 -( 0 : 0 : 0)
1520047 : 133 -( 0 : 0 : 0)
1520048 : 7 -( 0 : 0 : 0)
1520049 : 144 -( 0 : 0 : 0)
1520050 : 45 -( 0 : 0 : 0)
1520051 : 40 -( 0 : 0 : 0)
1520052 : 134 -( 0 : 0 : 0)
1520053 : 133 -( 0 : 0 : 0)
1520054 : 7 -( 0 : 0 : 0)
1520055 : 7 -( 0 : 0 : 0)
1520056 : 144 -( 0 : 0 : 0)
1520057 : 45 -( 0 : 0 : 0)
1520058 : 40 -( 0 : 0 : 0)
1520059 : 134 -( 0 : 0 : 0)
1520060 : 133 -( 0 : 0 : 0)
1520061 : 126 -( 0 : 0 : 0)
1520062 : 7 -( 0 : 0 : 0)
1520063 : 7 -( 0 : 0 : 0)
...
-------------------------------------

normal  mCurCall.funcId  sequence:
-------------------------------------
...
1520044 : 45 -( 0 : 0 : 0)
1520045 : 40 -( 0 : 0 : 0)
1520046 : 134 -( 0 : 0 : 0)
1520047 : 133 -( 0 : 0 : 0)
1520048 : 7 -( 0 : 0 : 0)
1520049 : 144 -( 0 : 0 : 0)
1520050 : 45 -( 0 : 0 : 0)
1520051 : 40 -( 0 : 0 : 0)
1520052 : 134 -( 0 : 0 : 0)
1520053 : 133 -( 0 : 0 : 0)
1520054 : 126 -( 0 : 0 : 0)
1520055 : 7 -( 0 : 0 : 0)
1520056 : 7 -( 0 : 0 : 0)
1520057 : 47 -( 0 : 0 : 0)
1520058 : 144 -( 0 : 0 : 0)
1520059 : 47 -( 0 : 0 : 0)
1520060 : 144 -( 0 : 0 : 0)
1520061 : 144 -( 0 : 0 : 0)
1520062 : 45 -( 0 : 0 : 0)
1520063 : 40 -( 0 : 0 : 0)
...
------------------------------------------------

**Comment by xinhuazhang1985** [comment]
GPU chip：  Mali-G52

**Comment by kexia01** [comment]
Maybe here are some ways to debug it.

Adding some info in in_file_mt.cpp: 
bool InFile::GetNextCall(void*& fptr, common::BCall_vlen& call, char*& src)
{
    if (unlikely(!mReadP || !mCurChunk))
        return false; // this should never happen

    if (mReadP >= mCurChunk->mData + mCurChunk->mLen)
        if (!MoveToNextChunk())
            return false;

    common::BCall tmpCall;
    tmpCall = *(common::BCall*)mReadP;
////////////////////////// here, print the call's funcId. ///////////////////////////
    if (unlikely(tmpCall.funcId > mMaxSigId))
    {
        DBG_LOG("funcId %d is out of range (%d max)!\n", (int)tmpCall.funcId, (int)mMaxSigId);
        return false;
    }
......
}

**Comment by xinhuazhang1985** [comment]
thank you @kexia01, I will try it.

**Comment by xinhuazhang1985** [comment]
HI

I add log info and try to reproduce this issue, another issue happen

sometime ，replay will stuck can not go on

error log ，please check it， thankyou

08-22 02:25:01.299  4430  4469 F paretrace64: [c4138907,f1049] Trying to copy client side buffer, but failed to fetch client side buffer 18313
08-22 02:25:01.301  4430  4469 I paretrace64: trace_executor.cpp,576: Failed to open output JSON /data/apitrace/result_file.txt: Permission denied
08-22 02:25:01.301  4430  4469 I paretrace64: trace_executor.cpp,405: Failed to output error log!

**Comment by xinhuazhang1985** [comment]
Hi 
I reproduce issue as @kexia01 said 

form here
funId: 4
funId: 4
funId: 4
funId: 126
 error happened...

log fragment as following
error funId：
...
funId: 4
funId: 4
funId: 4
funId: 126
funId: 144
funId: 144
funId: 43
funId: 43
funId: 133
funId: 44
funId: 134
funId: 10
funId: 144
funId: 144
funId: 133
funId: 44
funId: 134
funId: 10
funId: 144
funId: 144
funId: 133
funId: 44
funId: 134
funId: 10

normal funcId：
...
funId: 4
funId: 4
funId: 4
funId: 126
funId: 126
funId: 126
funId: 126
funId: 133
funId: 133
funId: 133
funId: 45
funId: 126
funId: 126
funId: 126
funId: 126
funId: 4
funId: 4
funId: 4
funId: 126
funId: 126
funId: 126
funId: 126
funId: 144
funId: 144
...

**Comment by kexia01** [comment]
I tried to reproduce this issue but it's a bit hard to do it.
Is there the issue if without snapshot option?
And, you could try preload option.

--ez preload  frame_start frame_end 
| Loads calls for frames between frame_start and frame_end into memory.

**Comment by kexia01** [comment]
Could trace file be retraced without -multithread -insequence?
