### ISSUE TITLE
high performance snapshot

### ISSUE THREAD

**Issue by popo919** [ARM-software/patrace#11]
Hi,
I found that when capturing GLES calls , there is a significant drop of frame rate from 60fps to 30fps. Is that normal? Any solution to get around such performance issue if I need to capture losslessly?

Thx.

**Comment by joakim-arm** [comment]
When tracing, some extra workload is added. So the application being traced will run at a lower frame rate. In your case, I am suspecting vsync to be the reason for dropping from 60 fps all the way down to 30 fps. Do you know if you app is barely above 60 fps when you are not tracing?

**Comment by popo919** [comment]
> When tracing, some extra workload is added. So the application being traced will run at a lower frame rate. In your case, I am suspecting vsync to be the reason for dropping from 60 fps all the way down to 30 fps. Do you know if you app is barely above 60 fps when you are not tracing?

Thanks for your reply, joakim. 

Yeah. The game loop is rather computation intensive.  However, actually, I only need to capture the final rendering result , so I trace and replay, and capture each frame .  Is there any way to capture final RGBA raw data rather than all the gles calls? (It is much cheaper to write a frame than dumping all gles calls, maybe.)

Thanks.

**Comment by joakim-arm** [comment]
Do I understand correctly that you are interested in the screenshot of the last frame in your .pat trace? If yes, then you need to know the frame number of the last frame.
If 1234 is your last frame, you can add the following paramter `-s 1234-999999/frame` if you are retracing on desktop. If you use the retracer on android, replace `*/frame` with `1234-999999/frame`.

> Is there any way to capture final RGBA raw data rather than all the gles calls?

Do you mean capturing screenshots while tracing?

**Comment by popo919** [comment]
Yes, I mean capturing while tracing. Is this available in the current workflow?

**Comment by joakim-arm** [comment]
Unfortunately, this is not supported out of the box. You can try to modify the tracer by removing the code that writes the gles calls to the trace and see if that increases the performance.

FYI, [Mali Graphics Debugger](https://developer.samsung.com/game/arm-mali) can also be used to capture screenshots (+ more). However, that one also comes with an performance overhead.

**Comment by popo919** [comment]
Yes, MGD is also slow in capturing, It seems I have to customize the tracer. Thanks for your support!
