### ISSUE TITLE
SIGSEGV in libinterceptor_patrace_arm.so library

### ISSUE THREAD

**Issue by dtoartist** [ARM-software/patrace#12]
Hi all,

I face the below error.

`14757 14757 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
 1840  1840 I /system/bin/tombstoned: received crash request for pid 8959
14757 14757 I crash_dump32: performing dump of process 8796 (target tid = 8959)
14757 14757 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
14757 14757 F DEBUG   : Build fingerprint: 'test/xxxxxxx/xxxxx/eng.B06038.20191104.204557:eng/release-keys'
14757 14757 F DEBUG   : Revision: '0'
14757 14757 F DEBUG   : ABI: 'arm'
14757 14757 F DEBUG   : pid: 8796, tid: 8959, name: RenderThread  >>> com.test.google.tv <<<
14757 14757 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
14757 14757 F DEBUG   : Cause: null pointer dereference
14757 14757 F DEBUG   :     r0  8ad7ea4c  r1  00000000  r2  0000001c  r3  00000004
14757 14757 F DEBUG   :     r4  ab93ad8c  r5  8b841464  r6  00000020  r7  8ad7ea08
14757 14757 F DEBUG   :     r8  00000000  r9  00000000  r10 8ad7eea8  r11 8b841464
14757 14757 F DEBUG   :     ip  80000000  sp  8ad7e9c8  lr  8b3064bb  pc  ab8a8dc8
 6154  6154 I AR_thread: type=1400 audit(0.0:545): avc: denied { ioctl } for path="/dev/binder" dev="tmpfs" ino=5483 ioctlcmd=0x6201 scontext=u:r:iptvmedia_hal:s0 
14757 14757 F DEBUG   : 
14757 14757 F DEBUG   : backtrace:
14757 14757 F DEBUG   :     #00 pc 00019dc8  /system/lib/libc.so (memcpy+68)
14757 14757 F DEBUG   :     #01 pc 0013b4b7  /vendor/lib/egl/libinterceptor_patrace_arm.so
14757 14757 F DEBUG   :     #02 pc 0009ecad  /vendor/lib/egl/libinterceptor_patrace_arm.so
14757 14757 F DEBUG   :     #03 pc 00132663  /vendor/lib/egl/libinterceptor_patrace_arm.so
14757 14757 F DEBUG   :     #04 pc 0005196b  /vendor/lib/egl/libinterceptor_patrace_arm.so
14757 14757 F DEBUG   :     #05 pc 00047cdd  /vendor/lib/egl/libinterceptor_patrace_arm.so
14757 14757 F DEBUG   :     #06 pc 00132bf1  /vendor/lib/egl/libinterceptor_patrace_arm.so
14757 14757 F DEBUG   :     #07 pc 000488bd  /vendor/lib/egl/libinterceptor_patrace_arm.so
14757 14757 F DEBUG   :     #08 pc 00064881  /vendor/lib/egl/libinterceptor_patrace_arm.so
14757 14757 F DEBUG   :     #09 pc 00064c0d  /vendor/lib/egl/libinterceptor_patrace_arm.so (glDrawArrays+32)
14757 14757 F DEBUG   :     #10 pc 0035536d  /system/lib/libhwui.so (GrMesh::sendToGpu(GrPrimitiveProcessor const&, GrMesh::SendToGpuImpl*) const+132)
`

I found the code line as below:
addr2line -Cfe obj/local/armeabi-v7a/libinterceptor_patrace_arm.so 0x0013b4b7
patrace/patrace/project/android/egltrace/jni/../../../../src/../../thirdparty/md5/md5.c:207
207     SET(a, b, c, d,  0,  7,  T1);

Did I do something wrong or missing?

**Comment by per-mathisen-arm** [comment]
That is not really enough information to debug the issue. How did you produce it?
