### ISSUE TITLE
Failed to open trace file: permission denied

### ISSUE THREAD

**Issue by lik88888** [ARM-software/patrace#13]
Hi all,

I am running patrace on an Hikey960 board with Android 9 (AOSP). I have an issue where the patrace complains that it fails to open the trace file to write. Here's what I see in the logcat:

01-03 23:59:47.459  4036  4056 I patrace64: egltrace.cpp,133: The trace file name is : /data/apitrace/com.android.gl2jni/com.android.gl2jni.1.pat
01-03 23:59:47.459  4036  4056 I patrace64: out_file.cpp,57: Failed to open file /data/apitrace/com.android.gl2jni/com.android.gl2jni.1.pat: Permission denied
01-03 23:59:47.496  4036  4061 I patrace64: out_file.cpp,140: cant write header when file is closed!

I don't see anything wrong with the permission of the path. Actually if I log into adb shell as a normal user (not root), I can write to that path:

hikey960:/ $ touch /data/apitrace/com.android.gl2jni/com.android.gl2jni.1.pat
hikey960:/ $ ls -l /data/apitrace/com.android.gl2jni/com.android.gl2jni.1.pat
-rw-rw---- 1 root sdcard_rw 0 2020-01-04 00:02 /data/apitrace/com.android.gl2jni/com.android.gl2jni.1.pat
hikey960:/ $ rm /data/apitrace/com.android.gl2jni/com.android.gl2jni.1.pat
hikey960:/ $

Any advice is highly appreciated,

Lik

**Comment by per-mathisen-arm** [comment]
Depending on the exact environment, one or more of the following things might help:
* adb shell setprop security.perf_harden 0
* chmod 777 /data/apitrace/com.android.gl2jni
* adb shell appops set com.arm.pa.paretrace READ_EXTERNAL_STORAGE allow
* adb shell appops set com.arm.pa.paretrace WRITE_EXTERNAL_STORAGE allow
* make /data/apitrace into a symlink to a directory in /sdcard

**Comment by lik88888** [comment]
I have some error applying these two:

adb shell appops set com.arm.pa.paretrace READ_EXTERNAL_STORAGE allow
adb shell appops set com.arm.pa.paretrace WRITE_EXTERNAL_STORAGE allow

It says "Error: No UID for com.arm.pa.paretrace in user 0"

The other options don't seem to help, unfortunately.

**Comment by solidpixel** [comment]
Try {{/sdcard/apitrace/}}, it tends to be less heavily locked down than {{/data/..}}.

**Comment by lik88888** [comment]
I got the issue resolved. Thanks a lot for everyone's help.

**Comment by per-mathisen-arm** [comment]
For people who might find this issue later, how did you resolve it?
