### ISSUE TITLE
Error while bulding patrace for android

### ISSUE THREAD

**Issue by noobmaster1109** [ARM-software/patrace#15]
[build.log](https://github.com/ARM-software/patrace/files/5020953/build.log)
Hi, I am getting errors while building PAtrace for android -
Executed the following command -
./scripts/build.py patrace android release

Error - 
Build eglretrace with Android-NDK...
##Generate C header for NativeAPI.java
ANDROID_JAR=/usr/local/xyz/home/abc/android-studio/adt-bundle-linux-x86_64-20140702/sdk//tools/../platforms/android-23/android.jar; \
    javac -classpath $ANDROID_JAR ./src/com/arm/pa/paretrace/NativeAPI.java; \
    javah -d jni -classpath $ANDROID_JAR:src com.arm.pa.paretrace.NativeAPI
Error: Could not find class file for 'com.arm.pa.paretrace.NativeAPI'.
make: *** [Makefile:25: callNdkBuild] Error 1
make: Leaving directory '/usr/local/xyz/home/abc/patrace/patrace/patrace/project/android/eglretrace'
The following command failed with error code 2:
make -j8 -C /usr/local/xyz/home/abc/patrace/patrace/scripts/../patrace/project/android/eglretrace

Can anyone help ? I'm new to this so not really sure what's going wrong
Attached is the full log.
[
[build.log](https://github.com/ARM-software/patrace/files/5020962/build.log)

**Comment by per-mathisen-arm** [comment]
Do you have the correct version of the NDK installed (as described in the manual)?

**Comment by mirocosphp** [comment]
I have the same error before. Check your java, javac, javah version using -version.
At that time I found my java and javah version are openjdk 9 but javac is jdk11。
if yours are not same. Use update-alternatives --config javac/java/javah to switch.
