### ISSUE TITLE
libeglretrece.so unaccess to libui.so during replay

### ISSUE THREAD

**Issue by Mirocos** [ARM-software/patrace#21]
I trace games on Android 10, And PaRetrace was built by Android-29 and NDK 21. When I tried to replay pat on Android 10, this error happens at anytime of replay. 
PaRetrace:        libeglretrace.so:unauthorized access to "system/lib64/libui.so"

I notice that document about Android 10 was updated recently, any advice about how to solve this problem?

**Comment by per-mathisen-arm** [comment]
Did you try the advice in patrace/doc/manual.md involving /etc/public.libraries.txt?
