### ISSUE TITLE
Fail to get gpu frequency, exynos 980

### ISSUE THREAD

**Issue by ylz-at** [ARM-software/patrace#22]
https://www.samsung.com/semiconductor/minisite/exynos/products/mobileprocessor/exynos-980/

**Comment by ylz-at** [comment]
I was trying on Android 10.

**Comment by per-mathisen-arm** [comment]
Hi, which phone is this?

**Comment by ylz-at** [comment]
Hi, I was testing on Vivo S6. It has Exynos 980 chip in it, and Exynos 980 is using Mali-G76.

**Comment by ylz-at** [comment]
Closing this as this tool requires root.
