### ISSUE TITLE
glReadBuffer with GL_BACK on offscreen rendering

### ISSUE THREAD

**Issue by sangmin-leee** [ARM-software/patrace#23]
Hi. While trying to use patrace, when I capture a trace file which contian glReadBuffer with GL_BACK and replay it with the offscreen option, it leads invalid API error.

So it's better to add a conditional branch on creating retrace_gles_auto.cpp.

```
        if func.name in ['glReadBuffer']:
            print '    RetraceOptions& opt = gRetracer.mOptions;'
            print '    if(opt.mForceOffscreen)'
            print '    {'
            print '         if(src == GL_BACK)'
            print '             src = GL_COLOR_ATTACHMENT0;'
            print '    }'
```

**Comment by per-mathisen-arm** [comment]
This has been fixed, thank you for your bug report!
