### ISSUE TITLE
About context state while retracing pat file

### ISSUE THREAD

**Issue by mirocosphp** [ARM-software/patrace#25]
Hi, I noticed in state.hpp file there has a Class named Context. In fact, I want to know is it possible to reload OpenGL Context such as when it comes to the n^th frame, I could save the context of the end of n^th frame and I can reload this context state wherever I need it?  Although I guess the Class Context is not the context that I think in OpenGL.  Any Advice would be helpful, thanks !!!

**Comment by per-mathisen-arm** [comment]
No, this is not really possible. The mentioned class only tracks a small portion of the GLES state. We have had the same idea several times in the past, but it is a very difficult problem and lots of questions whose answers depend on what exactly you want to do with it (eg how do you restore texture and buffer states? and what do you do with existing states? etc).
