### ISSUE TITLE
How to trace and retrace on Android 10

### ISSUE THREAD

**Issue by zxl5595** [ARM-software/patrace#27]
After build the project on Linux, I start to use it to trace game on Android fowllowing the manual. The game package name is "com.tencent.tmgp.sgame". 
1) However, when I run this game and stop it through Android UI and kill it, **nothing showed in the "/data/apitrace/com.tencent.tmgp.sgame"**.
2)When I install the apk **"/install/patrace/android/release/eglretrace/eglretrace-release.apk"**, **there is no button to select a trace file or start to retarace**.
![Screenshot_20210617_152124](https://user-images.githubusercontent.com/43431494/122352130-69f00300-cf81-11eb-83d6-dd8d294b660f.jpg)

Could anyone share you whole steps to trace and retrace?
===========================================================
Here is my whole steps to trace this game: 

**STEP 1: install fakedriver**
adb push /install/patrace/android/release/fakedriver/libGLES_wrapper_arm.so /sdcard/  
adb shell  
mount -o rw,remount /vendor  

cp /sdcard/libGLES_wrapper_arm.so /vendor/lib/egl/  
rm /sdcard/libGLES_wrapper_arm.so  
chmod 755 /vendor/lib/egl/libGLES_wrapper_arm.so  
mount -o ro,remount /vendor

**STEP 2: installing interceptor**
adb push install/patrace/android/release/egltrace/libinterceptor_patrace_arm.so /sdcard/  
adb push install/patrace/android/release/egltrace/libinterceptor_patrace_arm64.so /sdcard/  
adb shell  
mount -o rw,remount /vendor  

cp /sdcard/libinterceptor_patrace_arm.so /vendor/lib/egl/libinterceptor_patrace_arm.so  
cp /sdcard/libinterceptor_patrace_arm64.so /vendor/lib64/egl/libinterceptor_patrace_arm64.so  

chmod 755 /vendor/lib/egl/libinterceptor_patrace_arm.so  
chmod 755 /vendor/lib64/egl/libinterceptor_patrace_arm64.so  

echo "/vendor/lib/egl/libinterceptor_patrace_arm.so" > /vendor/lib/egl/interceptor.cfg  
echo "/vendor/lib64/egl/libinterceptor_patrace_arm64.so" > /vendor/lib64/egl/interceptor.cfg  

chmod 644 /vendor/lib/egl/interceptor.cfg  
chmod 644 /vendor/lib64/egl/interceptor.cfg  

mkdir /data/apitrace  
chmod 777 /data/apitrace

**STEP 3: enable GLES Layer** 
adb push /install/patrace/android/release/gleslayer/libGLES_layer_arm64.so /data/local/debug/gles
adb push /install/patrace/android/release/gleslayer/libGLES_layer_arm.so   /data/local/debug/gles

adb shell settings put global enable_gpu_debug_layers 1
adb shell settings put global gpu_debug_layers_gles libGLES_layer_arm64.so
adb shell settings put global gpu_debug_app  com.tencent.tmgp.sgame

**STEP 4: set the game pakeage ub applist**
adb shell
echo com.tencent.tmgp.sgame >> /system/lib/egl/appList.cfg
chmod 644 /system/lib/egl/appList.cfg  
mkdir -p /data/apitrace/com.tencent.tmgp.sgame
chmod 777 /data/apitrace/com.tencent.tmgp.sgame

**STEP 5:** 
run the game for about 2 mintues and then back to home page and kill the game through Android UI.

**Comment by per-mathisen-arm** [comment]
Hi. You should use either the interceptor or the gles layers - not both at the same time!

To figure out what is going on, you need to look at the logcat output. The interceptor will generate log messages tagged with 'fakedriver' while the gles layers will generate log messages tagged with 'gleslayer'. This will tell you if they were even active. If either was active, the next step is to look for messages tagged with patrace. Then you will see if was activated, and if so, where its output file was written.

**Comment by zxl5595** [comment]
> Hi. You should use either the interceptor or the gles layers - not both at the same time!
> 
> To figure out what is going on, you need to look at the logcat output. The interceptor will generate log messages tagged with 'fakedriver' while the gles layers will generate log messages tagged with 'gleslayer'. This will tell you if they were even active. If either was active, the next step is to look for messages tagged with patrace. Then you will see if was activated, and if so, where its output file was written.

------------------------------------------------------------------------
Thank you for your reply : ) , but there is still nothing showed.

I have **disable the gles layer** by:
1) rename the /data/local/debug folder （changed to /data/local/debug_bak).
2)reset the settings by:
  adb shell settings put global enable_gpu_debug_layers null
  adb shell settings put global gpu_debug_layers_gles null
  adb shell settings put global gpu_debug_app null

Then try Step 5 that I mentioned above again （run the game for serverl minutes and return to phone home page and kill the app). 
1) There is **nothing in the folder "/data/apitrace/com.tencent.tmgp.sgame/"**.  
2) Also I have no idea how the app **"PARetrace"** could be used (It **can't change the layout to be vertical**; I **didn't find anywhere to select the trace file and start retrace**).
3) How can I see the log you mentioned?

**Comment by per-mathisen-arm** [comment]
"adb logcat" is how you see the basic log in Android. I am sure there are other ways to see it as well. Android is hard and it may take a while to figure out. I don't see an actual issue here, though.

**Comment by zxl5595** [comment]
I don't think this issue could be closed., because I  STILL have problem to trace and retrace.
