### ISSUE TITLE
Can not debug paretrace.apk process on Android phone.

### ISSUE THREAD

**Issue by lovewsy** [ARM-software/patrace#28]
I try to debug paretrace on Android by gdb by following "Debugging the interceptor on Android" part in manual.md. But when I try to attach to remote target, the paretrace process running on Android is crashed, appearing no repondng message.

I noticed that the libs in manual.md, such as libinterceptor_patrace.so, can not be found, Is this manual outdated?
Please help check whether the guideline for debugging paretrace on Android is still working.

**Comment by per-mathisen-arm** [comment]
Title says _retracer_, but you seem to be following the guide to debug the _tracer_, so I think this is where the confusion lies.
