### ISSUE TITLE
"undefinded symbol eglGetProcAddress" while retracing on desktop linux

### ISSUE THREAD

**Issue by lovewsy** [ARM-software/patrace#30]
I try retrace the pat file traced on android on desktop linux, I installed Mali_OpenGL_ES_Emulator-v3.0.4-2 successfully.

However an error occurs when I try to execute paretrace
![paretrace_linux](https://user-images.githubusercontent.com/41018796/127132923-265c6082-3a35-4f41-ace5-cff9c1142c0b.png)

I can't figure out how to solve this issue, could anyone help me get rid of that? Thanks

**Comment by per-mathisen-arm** [comment]
Why are you using the Mali OpenGL ES Emulator? I haven't tried using that myself for years, and I think it is no longer being actively developed. I would recommend using a proper OpenGL ES implementation.
