### ISSUE TITLE
why does the pat_editor tool still use RA instead of MT?

### ISSUE THREAD

**Issue by Mirocos** [ARM-software/patrace#32]
Sometimes when I tried to extract data from a pat which has large size like 2GB, editor would straightly crashed with core dumped. I think it's because the RA format need to generate almost 3 times size of pat to make the extraction work. I realized the retrace process has already using MT instead of RA, so I suggest pat_editor could do that as well. If so, it needs to make some change in tools/pat_editor、 common/trace_mode.cpp.

**Comment by per-mathisen-arm** [comment]
Are you on a 32-bit system? Or very memory limited? The reason for RA is to enable writing out changes from entire frames (or more) at once, while MT only has a small chunk of data in memory at any time.

**Comment by Mirocos** [comment]
64-bit of Ubuntu18.04LTS。system memory totally 64GB



发自我的iPhone


------------------ Original ------------------
From: Per ***@***.***&gt;
Date: Mon,Aug 16,2021 9:12 PM
To: ARM-software/patrace ***@***.***&gt;
Cc: ze-ming ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ARM-software/patrace] why does the pat_editor tool still use RA instead of MT? (#32)





 
Are you on a 32-bit system? Or very memory limited? The reason for RA is to enable writing out changes from entire frames (or more) at once, while MT only has a small chunk of data in memory at any time.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
