### ISSUE TITLE
Does forceSingleWindow mode still work?

### ISSUE THREAD

**Issue by Mirocos** [ARM-software/patrace#33]
I want to retrace some pat through forceSingleWindow mode. However, program always crashed at _shareContext check.
I tried to use tool 'single_surface' to convert multi surface to single surface pat. But that tool always failed with error like below:
```bash
in_file_ra.cpp,149: Creating temporary random access file com.miHoYo.Yuanshen.2.pat.ra
in_file_ra.cpp,37: Failed to open file com.miHoYo.Yuanshen.2.pat.ra
single_surface.cpp,396: Failed to open for reading: com.miHoYo.Yuanshen.2.pat

```

Does forceSingleWindow mode still work? Or are there something I missed to make that mode work?

Here is my retrace_parameters.json:
```json
{
   "colorBitsRed" : 8,
   "colorBitsGreen" : 8,
   "colorBitsBlue" : 8,
   "colorBitsAlpha" : 8,
   "depthBits" : 24,
   "stencilBits" : 8,
   "forceSingleWindow" : true,
   "threadId": 3,
   "overrideResolution" : true,
   "overrideWidth" : 1920,
   "overrideHeight" : 1080,
   "offscreen" : false,
   "frames" : "0-20000000",
   "file" : "com.miHoYo.Yuanshen.2.pat",
   "preload" : true,
   "landscape" : true
}
```

size of pat file is 1.5GB
And my system os is Ubuntu18.04LTS
system memory totally 64GB

**Comment by per-mathisen-arm** [comment]
It is supposed to work, yes. Although we are currently in the process of phasing it out in favour of a "singlesurface" header parameter but that is still in a bit of a work in progress. The single_surface tool error looks very strange - is it running out of disk space or something? I would recommend trying to run the trace in multithread mode. If you can share the trace file, I could have a look at it.

**Comment by Mirocos** [comment]
Thanks for your reply, but I cannot share the trace file with you for some reason. The single_surface error caused by std::ifstream that cannot not open the trace file is really weird while my disk space is sufficient . However, I found that with parameter "singlesurface" in multithread mode, the trace window can hold in one surface which is what I actually expected.

**Comment by per-mathisen-arm** [comment]
So it works now and I can close this ticket?

**Comment by Mirocos** [comment]
yes，please



发自我的iPhone


------------------ Original ------------------
From: Per ***@***.***&gt;
Date: Tue,Aug 24,2021 9:55 PM
To: ARM-software/patrace ***@***.***&gt;
Cc: ze-ming ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ARM-software/patrace] Does forceSingleWindow mode still work? (#33)





 
So it works now and I can close this ticket?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
