### ISSUE TITLE
some doubts about format of trace file

### ISSUE THREAD

**Issue by Mirocos** [ARM-software/patrace#34]
Hi, I read the manual document and there shows the format of trace file first begin with the common header, then the sigbook, final the actually call.

But when I read the source code  of function OpenTraceFile() in in_file_mt.cpp, I found retrace decode the trace file with following order:
1. common header
2. first chunk
3. sigbook
4. other chunks

where the start of sigbook is the beginning of first chunk, that is what confused me. So what is the actually order in trace file, or is there something I just missed?

**Comment by Mirocos** [comment]
first call GetNextCall(...) will convert first chunk to a Call.

**Comment by Mirocos** [comment]
Or the fist chunk contains the data of sigbook and the data of fist call?

**Comment by per-mathisen-arm** [comment]
Yes, the first chunk contains the sigbook.
