### ISSUE TITLE
Android build issue : make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by 13820086858** [ARM-software/patrace#4]
xinhua.zhang@tj02759lab276u:~/Downloads/patrace/patrace$ ./scripts/build.py patrace android release
Using ndk-build: /home/xinhua.zhang/Downloads/android-ndk-r13b
Command : cmake -DSRC_ROOT=/home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/src -DPATRACE_VERSION_MAJOR=2 -DPATRACE_VERSION_MINOR=13 -DPATRACE_VERSION_PATCH=0 -DPATRACE_REVISION=unofficial -DPATRACE_VERSION_TYPE=dev -DTEST_LIBRARY= -DCMAKE_VERBOSE_MAKEFILE=TRUE -P /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/cmake/egltrace/config.cmake

Current directory : /home/xinhua.zhang/Downloads/patrace/patrace
Command : cmake -DSRC_ROOT=/home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/src -DPATRACE_VERSION_MAJOR=2 -DPATRACE_VERSION_MINOR=13 -DPATRACE_VERSION_PATCH=0 -DPATRACE_REVISION=unofficial -DPATRACE_VERSION_TYPE=dev -DTEST_LIBRARY= -DCMAKE_VERBOSE_MAKEFILE=TRUE -P /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/cmake/egltrace/config.cmake

Command : sed -i -e "s/\(<string name=\"version\">\).*\(<\/string>\)/\1r2p13 unofficial dev\2/g" /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/eglretrace/res/values/strings.xml

Current directory : /home/xinhua.zhang/Downloads/patrace/patrace
Command : sed -i -e "s/\(<string name=\"version\">\).*\(<\/string>\)/\1r2p13 unofficial dev\2/g" /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/eglretrace/res/values/strings.xml

Command : sed -i -e "s/\(android:versionCode=\"\)[0-9]*/\12130/g" /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/eglretrace/AndroidManifest.xml

Current directory : /home/xinhua.zhang/Downloads/patrace/patrace
Command : sed -i -e "s/\(android:versionCode=\"\)[0-9]*/\12130/g" /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/eglretrace/AndroidManifest.xml

Command : android update project --name android_assets --target android-23 --path /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../thirdparty/libcollector/android/gradle/collector_android/android_assets

Current directory : /home/xinhua.zhang/Downloads/patrace/patrace
Command : android update project --name android_assets --target android-23 --path /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../thirdparty/libcollector/android/gradle/collector_android/android_assets

Updated and renamed default.properties to project.properties
Updated local.properties
Added file /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../thirdparty/libcollector/android/gradle/collector_android/android_assets/build.xml
Added file /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../thirdparty/libcollector/android/gradle/collector_android/android_assets/proguard-project.txt
Command : android update project --name eglretrace --target android-23 --path /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/eglretrace

Current directory : /home/xinhua.zhang/Downloads/patrace/patrace
Command : android update project --name eglretrace --target android-23 --path /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/eglretrace

Updated and renamed default.properties to project.properties
Updated local.properties
Added file /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/eglretrace/build.xml
Added file /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/eglretrace/proguard-project.txt
Command : android update project --name template --target android-23 --path /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/integration_tests/template

Current directory : /home/xinhua.zhang/Downloads/patrace/patrace
Command : android update project --name template --target android-23 --path /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/integration_tests/template

Updated and renamed default.properties to project.properties
Updated local.properties
Added file /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/integration_tests/template/build.xml
Added file /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/integration_tests/template/proguard-project.txt
**********************************************************************
Building patrace/egltrace
**********************************************************************
Command : make -j8 -C /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/egltrace

Current directory : /home/xinhua.zhang/Downloads/patrace/patrace
Command : make -j8 -C /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/egltrace

make: Entering directory '/home/xinhua.zhang/Downloads/patrace/patrace/patrace/project/android/egltrace'
make: *** No targets specified and no makefile found.  Stop.
make: Leaving directory '/home/xinhua.zhang/Downloads/patrace/patrace/patrace/project/android/egltrace'
The following command failed with error code 2:
make -j8 -C /home/xinhua.zhang/Downloads/patrace/patrace/scripts/../patrace/project/android/egltrace

**Comment by per-mathisen-arm** [comment]
Thanks a lot for reporting this. Our source export was a bit broken by a bad gitignore. It should be fixed now.
