### ISSUE TITLE
Compilation errors building on Fedora 35

### ISSUE THREAD

**Issue by ehwelbon** [ARM-software/patrace#41]
Building on Fedora 35 and have these compilation errors:

166 /home/edwel1109/my_droid/patrace/thirdparty/libpng/pngprefix.h:141:27: error: ‘number_buf’ may be used uninitialized [-Werror=maybe-uninitialized]
209 /home/edwel1109/my_droid/patrace/thirdparty/libcollector/collectors/perf.cpp:425:25: error: loop variable ‘pair’ creates a copy from type ‘const std::pair<const std::__cxx1
1::basic_string<char>, CollectorValueList>’ [-Werror=range-loop-construct]
216 /home/edwel1109/my_droid/patrace/thirdparty/libcollector/collectors/perf.cpp:436:29: error: loop variable ‘pair’ creates a copy from type ‘const std::pair<const std::__cxx1
1::basic_string<char>, CollectorValueList>’ [-Werror=range-loop-construct]  

[build-errors-patrace.txt](https://github.com/ARM-software/patrace/files/8644106/build-errors-patrace.txt)

**Comment by ehwelbon** [comment]
If I want to play back a trace don't I need the above to build?  Sorry if it's noob questtion but it's not obvious what is wrong.

**Comment by per-mathisen-arm** [comment]
Thanks for the report! I will look into these warnings. In the meantime, you can just remove the -Werror from patrace/projects/cmake/CMakeLists.txt to get it to build.

**Comment by ehwelbon** [comment]
[build-errors-patrace.2.txt](https://github.com/ARM-software/patrace/files/8691298/build-errors-patrace.2.txt)
I tried that but it didn't work, the previous warning about warnings treated as errors is now gone but it still didn't build.  From what I can see it is failing at the following (but do look at the log)
Executing swig -python -c++ -outdir /home/edwel1109/patrace/patrace/python/pypatrace -o patrace_wrap.cpp /home/edwel1109/patrace/patrace/python/pypatrace/patrace.i
Traceback (most recent call last):
  File "/home/edwel1109/patrace/patrace/python/pypatrace/setup.py", line 23, in <module>
    subprocess.call(command.split())
  File "/usr/lib64/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'swig'

**Comment by per-mathisen-arm** [comment]
You need to install swig. See patrace/doc/manual.md for a list of needed packages.

**Comment by ehwelbon** [comment]
OK I missed swig but I believe I have all the others installed.  I now get this build error:

[ 92%] Building CXX object tool/CMakeFiles/analyze_trace.dir/home/edwel1109/patrace/patrace/src/retracer/eglconfiginfo.cpp.o
/home/edwel1109/patrace/patrace/src/tool/pat_editor/merge.cpp: In function ‘void setValueTM(common::ValueTM*&, const std::string&, const Json::Value&, const std::string&)’:
/home/edwel1109/patrace/patrace/src/tool/pat_editor/merge.cpp:199:28: error: ‘numeric_limits’ was not declared in this scope
  199 |                 fin.ignore(numeric_limits<streamsize>::max());
      |                            ^~~~~~~~~~~~~~

Note that I had to upgrade to FC36, I don't think it matters but I did do a "clean" before I rebuilt with "release"

[build-errors-patrace.7.txt](https://github.com/ARM-software/patrace/files/8751425/build-errors-patrace.7.txt)

**Comment by per-mathisen-arm** [comment]
Can you try to add "#include <limits>" at the top of this file? Please let me know if this fixes the problem.

**Comment by ehwelbon** [comment]
OK will try adding "#include " at the top of /home/edwel1109/patrace/patrace/src/tool/pat_editor/merge.cpp

**Comment by pleasurefish** [comment]
maybe this patch can fix this issue.
https://github.com/pleasurefish/patrace/commit/e3ef2817f7380c667d4d77c544749f95f08cb701

**Comment by per-mathisen-arm** [comment]
Thanks, the fixes in the patch are already included in the latest internal version and will be in the next release.  Somehow github removed parts of my earlier comment. The include header you need is 'limits', I think. Lets see if this works:
`#include <limits>`

**Comment by ehwelbon** [comment]
Hi PER, I no longer need to use the tool but thanks for getting back with
me!
