### ISSUE TITLE
Cannot remount /vendor as read-only on Android 10 / API 29 device which precludes tracing

### ISSUE THREAD

**Issue by ehwelbon** [ARM-software/patrace#42]
In order to install the interceptor file manual.md instructs as follows:

    adb shell  
    su  
    mount -o rw,remount /vendor  
    cp /sdcard/libinterceptor_patrace_arm.so /vendor/lib/egl/libinterceptor_patrace_arm.so 

However there is **no** su on the device I am using, as an apparent result the remount does not work and the cp fails.   

    # su
    /system/bin/sh: su: inaccessible or not found 
    # mount -o rw,remount /vendor
    '/dev/block/dm-3' is read-only
    # cp /sdcard/libinterceptor_patrace_arm.so  /vendor/lib/egl/libinterceptor_patrace_arm.so                                                                            
    cp: /vendor/lib/egl/libinterceptor_patrace_arm.so: Read-only file system

I have tried a number of variations on the mount.  I even considered completely unmounting and mounting but the umount fails since /vendor is in use.  I get this from prop, id, and ls and mount on /vendor.

    # getprop ro.treble.enabled
    true
    # id
    uid=0(root) gid=0(root)  groups=0(root),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:su:s0
    # ls -lsd /vendor                                                                                                                                                                
    4 drwxr-xr-x 13 root shell 4096 2008-12-31 16:00 /vendor
    # mount | grep /vendor
    /dev/block/dm-3 on /vendor type ext4 (ro,seclabel,relatime,discard,errors=remount-ro)

The document intimates that this has been tested on Android 10, what am I missing?   Unless I can write to /vendor, it appears that tracing is not possible.

**Comment by per-mathisen-arm** [comment]
You need to root the device first.

**Comment by ehwelbon** [comment]
It is development device and is not physically present, I only have adb access to the device.   Is there some way to definitively ascertain that the device is rooted or not?

**Comment by per-mathisen-arm** [comment]
I think if there is no 'su' then it is not rooted.
