### ISSUE TITLE
limit the replay speed on android

### ISSUE THREAD

**Issue by simpzan** [ARM-software/patrace#43]
I found the replay fps is much faster than the fps when captured. 
I need to use patrace to simulate the GPU workload of the honor of kings game, so I want the replayed frames to be in the same render pace with the render pace of original captured game.
Is it possible to make replay app use the same render pace of the original captured app/game?

Thanks in advance!

**Comment by per-mathisen-arm** [comment]
It is an interesting idea, but we do not have support for this yet. Feel free to add this feature to patrace!

**Comment by simpzan** [comment]
@per-mathisen-arm Thanks for the reply.
I am curious if patrace record the relative timestamp of each captured frame and use the timestamp to control the pace of replay? How the replay app controls the render pace of each frame in the current implementation?

**Comment by per-mathisen-arm** [comment]
No, per-frame timestamps are not recorded during capture, but in the latest version we will record a trace fps. During replay it will play the trace as fast as possible, and it will not attempt to impose a render pace.
