### ISSUE TITLE
Trace on dimensity 9000+

### ISSUE THREAD

**Issue by Mirocos** [ARM-software/patrace#45]
I install the fakedriver and interceptor on a machine with MTK Dimensity 9000+ chip。 Before that , I have succeed to trace on a machine with MTK Dimensity 9000 chip.(Both on Android 12)

When I used `adb logcat | grep -i "patrace"`, "9000+" didn't log anything. It seems that PaTrace didn't not capture the process name that configed in `appList.cfg`。For example, Genshin Impact and Honor of Kings, etc.

Does anything I can do to trace on MTK Dimensity 9000+ machine?

**Comment by kexia01** [comment]
You could search fakedriver in logcat to see whether the fakedriver was loaded.
And could you post the logcat.
