### ISSUE TITLE
failed to trace the chromium under wayland environment

### ISSUE THREAD

**Issue by pleasurefish** [ARM-software/patrace#46]
i was capturing a trace under wayland environment, but it failed, while it is sucessful to small gles app.
did you ever run such situation before?

$ LD_PRELOAD=/usr/lib/libegltrace.so OUT_TRACE_FILE=chromium.trace chromium --use-gl=egl --disable-accelerated-video-decode --disable-setuid-sandbox  http://10.192.241.30:8000/conformance-suites/2.0.0/conformance/misc/type-conversion-test.html?webglVersion=2&dumpShaders=undefined&quiet=0
[2] 1715
[3] 1716
root@machine:~# egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
egltrace.cpp,2115: PaTrace init version: r4p2 dev unofficial
tracerparams.cpp,64: Warning: tracerparams.cfg does not exist!
[1715:1772:0428/200314.689120:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

**Comment by per-mathisen-arm** [comment]
I have been able to trace Chrome on Linux desktop in the past with --allow-sandbox-debugging --allow-unsecure-dlls --disable-gpu-sandbox --disable-namespace-sandbox  --disable-vulkan-fallback-to-gl-for-testing --disable-seccomp-filter-sandbox --disable-setuid-sandbox --no-sandbox. You might need to disable some more security stuff to get it to work.

**Comment by pleasurefish** [comment]
thanks, mathisen.
