### ISSUE TITLE
Is fakedriver able to trace on Adreno GPU?

### ISSUE THREAD

**Issue by wsyOverflow** [ARM-software/patrace#48]
I have generated pat file on Mali GPU. But I failed to try trace on Adreno GPU. Is fakedriver able to trace on Adreno GPU?

**Comment by per-mathisen-arm** [comment]
Fakedriver might only work on Mali, it is the only platform we've tested it on and it is bit of an ugly hack. You might want to try the GLES layers approach to tracing instead.

**Comment by wsyOverflow** [comment]
> 

Thanks for your replying. I have no experience working in the dirver layer. Could you give some advices about implementing tracing on Adreno GPU? Is there any related open-source project?

**Comment by per-mathisen-arm** [comment]
The patrace documentation explains how to install it for tracing using GLES layers. Please try this. You should not need to implement anything new.

**Comment by wsyOverflow** [comment]
> 
I apology for the misunderstanding. Thanks for your detailed explanation
