### ISSUE TITLE
fastforwarder binds EBO before bind VAO

### ISSUE THREAD

**Issue by BuryFlowers** [ARM-software/patrace#56]
I tried fastforwarded to save OpenGL fbo context for me.

But glDrawElements kept collapsing because it didnt have EBO bound.

I moved the codes in fastforwarder.cpp from line 2584 to 2588 below line 2604, so OpenGL will bind VAO before bind EBO.

The codes is now as below:

        // vao
        _glGetIntegerv(GL_VERTEX_ARRAY_BINDING, &mVAO);
        mCmdEmitter.emitBindVertexArray(0);

        // vertex attribute
        _glGetVertexAttribiv(0, GL_VERTEX_ATTRIB_ARRAY_ENABLED, &mVA0En);
        _glGetVertexAttribiv(0, GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING, &mVA0VertexBuffer);
        _glGetVertexAttribIiv(0, GL_VERTEX_ATTRIB_ARRAY_INTEGER, &misVA0Integer);
        _glGetVertexAttribIiv(0, GL_VERTEX_ATTRIB_ARRAY_SIZE, &mVA0Size);
        _glGetVertexAttribIiv(0, GL_VERTEX_ATTRIB_ARRAY_TYPE, &mVA0Type);
        _glGetVertexAttribIiv(0, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED, &mVA0Normalized);
        _glGetVertexAttribIiv(0, GL_VERTEX_ATTRIB_ARRAY_STRIDE, &mVA0Stride);
        _glGetVertexAttribPointerv(0, GL_VERTEX_ATTRIB_ARRAY_POINTER, &mVA0Pointer);
        mCmdEmitter.emitVertexAttibPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0);
        mCmdEmitter.emitEnableVertexAttribArray(0);

        GLuint index[] = {0, 1, 2, 0, 2, 3};
        mIB = mVB + 1;
        mCmdEmitter.emitGenBuffers(1, &mIB);
        mCmdEmitter.emitBindBuffer(GL_ELEMENT_ARRAY_BUFFER, mIB);
        mCmdEmitter.emitBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(index), index, GL_STATIC_DRAW);

Then it seems go well, but I dont know whether it is a bug.

**Comment by kexia01** [comment]
Thanks.
Have merged to r5p2
