### ISSUE TITLE
Crash when replay Genshin Impact

### ISSUE THREAD

**Issue by sivese** [ARM-software/patrace#57]
I tried to replay Genshin Impact after capturing it. But after about 1 and a half minutes, patrace crashed and exited.

For this problem, I'm guessing that memory is the cause. Because when I profiled it, the patrce was taking up too much memory over 4 GB. Also, it claims additional memory continuously.

Please let me know what is the problem.

**Comment by BuryFlowers** [comment]
Maybe you can use "clientsidetrim" tool in the "tool" folder.
It will insert "glDeleteCilentSideBuffer" calls to delete useless buffer in the pat file while replaying. Then, the new pat file it generates may not use too much memory.
