### ISSUE TITLE
trace file replay issue

### ISSUE THREAD

**Issue by xinhuazhang1985** [ARM-software/patrace#6]
When I replay GFXbench-manhatan trace files and simultaneous monitoring eglApi.cpp, I found that there were three API(eglSwapBuffers / eglSwapBuffersWithDamageKHR) calls for each snap frame, is that normal ?

rreplay trace adb shell command: 
adb shell 'am start -n com.arm.pa.paretrace/.Activities.RetraceActivity --ez multithread true --ez insequence true --ez force_single_window false --es fileName "/sdcard/apitrace/trace_repo/com.samsung.sdet.benchmark.manhattan.pat" --es snapshotPrefix "/sdcard/egl_dump/" --es snapshotCallset "*/frame"'

**Comment by per-mathisen-arm** [comment]
That sounds a bit weird. Does it also happen if you do not use the multithread option?

**Comment by xinhuazhang1985** [comment]
when eglretrace.apk view is GLTextureView (force_single_window = false)
this case will happen

and from systrace of eglretrace replay, I found :
For each snap frame,
renderThread call two times of eglSwapBuffersWithDamageKHR
JNIsurfaceTextrue call one time of eglSwapBuffersWithDamageKHR

when eglretrace.apk view is GLSurfaceView ,   only one time API(eglSwapBuffers / eglSwapBuffersWithDamageKHR) call for each snap frame.

**Comment by per-mathisen-arm** [comment]
This issue got a bit lost. If you can still see this happening with the latest release, please reopen this ticket. Sorry!
