### ISSUE TITLE
Tracing 64-bit apps on Galaxy S10

### ISSUE THREAD

**Issue by yyang29** [ARM-software/patrace#7]
I want to trace a 64-bit app on Galaxy S10 (ARM GPU). I have followed the instructions to build the libraries. Also, I installed the fake driver with:

adb push libGLES_wrapper_arm64.so /vendor/lib64/egl/
mv /vendor/lib64/egl/libGLES_mali.so /vendor/lib64/egl/lib_mali.so
chmod 755 /vendor/lib64/egl/libGLES_wrapper_arm64.so

/vendor/lib64/egl # ls
appList.cfg
libGLES_wrapper_arm64.so
libinterceptor_patrace_arm64.so 
interceptor.cfg lib_mali.so

But when I run the app, it says:

couldn't find an OpenGL ES implementation, make sure you set ro.hardware.egl or ro.board.platform
Aborted

Is there anything missing in my setup? lib_mali.so is renamed from libGLES_mali.so. If I revert this (rename lib_mali.so back to libGLES_mali.so) everything works.

**Comment by yyang29** [comment]
I further renamed *libGLES_wrapper_arm64.so* to libGLES_mali.so, I hit a different error. It's a seg fault.
logcat shows that the fakedriver64 is being called now. How could I debug further?

**Comment by per-mathisen-arm** [comment]
Installing the fakedriver is always tricky. We have made it work on an S10 here, so it should work eventually.

Try to not move or rename the libGLES_mali.so - I am not sure this works anymore in Android Q. You may also have to use /system/vendor

**Comment by per-mathisen-arm** [comment]
You can try this recipe:

adb push fakedriver/libGLES_wrapper_arm64.so /sdcard/  
adb shell  
su  
mount -o rw,remount /system
cp /sdcard/libGLES_wrapper_arm64.so /system/vendor/lib64/egl/
rm /sdcard/libGLES_wrapper_arm64.so
chmod 755 /system/vendor/lib64/egl/libGLES_wrapper_arm64.so
mount -o ro,remount /system

**Comment by yyang29** [comment]
Thanks Per.

If I don't remove or rename the libGLES_mali.so, everything works, but I don't think fakedriver64 is being called at all.

Regarding to your second suggestion, I found that the content in /system/vendor/lib64/egl/ is always in sync with the content in /vendor/lib64/egl.

Any other suggestions?

**Comment by per-mathisen-arm** [comment]
Can you check if treble is enabled with 'getprop ro.treble.enabled'?
If so, try see if 'cp /system/lib64/libstdc++.so /vendor/lib64/' might help.
