### ISSUE TITLE
Tracing on Nexus 6 (Adreno GPU)

### ISSUE THREAD

**Issue by hedejing** [ARM-software/patrace#9]
I want to trace an app on Nexus 6 (Adreno GPU). I have followed the instructions in the manual to build the libraries and install fakedriver and interceptor. But after I ran and closed the app, no "Close trace file" showed up in logcat and no trace file was created.

I had tried setting FlushTraceFileEveryFrame to true in tracerparams.cfg, but still nothing was created.

I noticed that in /project/android/egltrace/ there is an README which says "After reboot, the interceptor will be enabled", but when I reboot Nexus was stuck on Google logo at start up and I had to flash it..

So I think maybe PATrace does not support for Adreno GPU? (since the implementation of Interceptor is related to Mali drivers?) If I want to use PATrace, is mobiles with Mail GPU a better choice?

**Comment by joakim-arm** [comment]
Unfortunately, we have not used and tested the tracer for other GPUs than Mali.

**Comment by hedejing** [comment]
Got it. Thanks for your reply.

**Comment by joakim-arm** [comment]
However, the retracer should work on any Android device.
